DROP DATABASE IF EXISTS storedb;
DROP ROLE IF EXISTS storeuser;

CREATE USER storeuser;
ALTER USER storeuser WITH ENCRYPTED PASSWORD 'storepass';
CREATE DATABASE storedb WITH ENCODING 'UNICODE' OWNER storeuser;